include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    flutter_style_todos: false
    avoid_redundant_argument_values: false
    sort_pub_dependencies: false