name: pet_heaven
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_riverpod: ^2.1.3
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  meta: ^1.8.0
  riverpod_annotation: ^1.0.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  mocktail_image_network: ^0.3.1

dependency_overrides:
  analyzer: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  hive_test: ^1.0.1
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^3.1.0
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/