name: pet_heaven
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter_riverpod: ^2.1.3
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  meta: ^1.8.0
  riverpod_annotation: ^2.3.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  mocktail_image_network: ^1.1.0
  flex_color_scheme: ^8.0.2
  confetti: ^0.8.0

dependency_overrides:
  analyzer: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  hive_test: ^1.0.1
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.9
  very_good_analysis: ^6.0.0
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/